### ISSUE TITLE
Dashboard memory leak over time

### ISSUE THREAD

**Issue by emlaurora** [shukriadams/arewedown#18] opened 2022-01-24 10:34 UTC
I noticed that if I keep the web page opened for several hours with the "reload" activated, at the beginning the memory footprint is about 400MB while at the end it becomes more than 4GB, forcing to manually refresh the page to drop all those wasted memory.

Maybe there is some kind of memory leak at each "reload"?

**Comment by shukriadams** [comment] 2022-01-24 17:24
Thanks for reporting - I'll look into it ASAP.

**Comment by shukriadams** [comment] 2023-01-03 09:22
This should be fixed with 0.3.0. The memory like was most likely caused by infinitely bounding event handlers in the iframe reload system - this is now completely rewritten. Assuming fixed, but feel free to reflag if necessary.

**Closed by shukriadams** 2023-01-03 09:22 UTC
Labels: bug
